#!/bin/sh

OS="macOS"

# NAVIAGTE TO WORKING DIRDCTORY OF THIS SCRIPT
cd `dirname "$0"`

# SETUP PACKAGE MANAGER
if [ "$OS" == "macOS" ] ; then
    PACKAGE_MANAGER="brew"
    CONF="/Users/vinc/.config"
    ./setup_mac
elif [ "$OS" == "arch" ] ; then
    PACKAGE_MANAGER="pacman"
    CONF="/home/vinc/.config"
    # ./setup_arch
else
    PACKAGE_MANAGER=""   # TODO
fi

# INSTALL PACKAGES
# $PACKAGE_MANAGER install $(cat ./packages.txt)
pip install --upgrade pip
pip3 install -r ./packages_pip.txt 
# for i in $(cat packages_npm.txt); do
#     npm install -g "$i"; 
# done
# nvim -c PlugInstall

git clone git@github.com:alexanderjeurissen/ranger_devicons.git $CONF/ranger/plugins/ranger_devicons
# git clone git@github.com:emscripten-core/emsdk.git $CONF/emsdk


# TMUX
mkdir $CONF/tmux/plugins
git clone git@github.com:tmux-plugins/tpm.git $CONF/tmux/plugins/tpm
mkdir $CONF/tmux/resurrect_saves
ln -s $CONF/tmux/resurrect_saves ~/.tmux/resurrect


# zsh + oh-my-zsh  (+ syntax hl)
git clone git@github.com:ohmyzsh/ohmyzsh.git $CONF/zsh/oh-my-zsh
git clone git@github.com:zsh-users/zsh-syntax-highlighting.git $CONF/zsh/oh-my-zsh/plugins/zsh-syntax-highlighting

# rust & cargo  (+ rls)
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# rustup component add rls rust-analysis rust-src

# emacs + doom
# sudo rm -r ~/.emacs.d
# git clone --depth 1 https://github.com/vincentmader/doom-emacs ~/.emacs.d
# ~/.emacs.d/bin/doom install



# PERSONAL FILES
# git clone https://github.com/vincentmader/org ~/org
# git clone --recurse-submodules https://github.com/vincentmader/code ~/code
# git clone --recurse-submodules https://github.com/vincentmader/docs ~/docs
# pull config repos from GitHub
git clone --recurse-submodules git@github.com:vincentmader/config-dotfiles.git $CONF
git clone git@github.com:vincentmader/dmenu.git $CONF/dmenu
git clone git@github.com:vincentmader/dwm.git $CONF/dwm
git clone git@github.com:vincentmader/st.git $CONF/st
