start:
	brew services start yabai	
	brew services start skhd
restart:
	brew services restart yabai	
	brew services restart skhd
show_windows:
	yabai -m query --windows
yabai:  # NOTE not needed anymore
	yabai
