#!/usr/bin/env sh

# The scripting-addition must be loaded manually if you are running 
# yabai on macOS Big Sur. Uncomment the following line to have the 
# injection performed when the config is executed during startup.
#
# For this to work you must configure sudo such that it will be able to 
# run the command without password, see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ╭───────────────────────────────────────────────────────────────────────────╮
# │                               Global settings                             │
# ╰───────────────────────────────────────────────────────────────────────────╯

    yabai -m config mouse_follows_focus          off
    yabai -m config focus_follows_mouse          on
    yabai -m config window_origin_display        default
    yabai -m config window_placement             second_child
    yabai -m config window_topmost               off
    yabai -m config window_shadow                on
    yabai -m config window_opacity               off
    yabai -m config window_opacity_duration      0.0
    yabai -m config active_window_opacity        1.0
    yabai -m config normal_window_opacity        0.90
    yabai -m config window_border                off
    yabai -m config window_border_width          6
    yabai -m config active_window_border_color   0xff775759
    yabai -m config normal_window_border_color   0xff555555
    yabai -m config insert_feedback_color        0xffd75f5f
    yabai -m config split_ratio                  0.50
    yabai -m config auto_balance                 off
    yabai -m config mouse_modifier               fn
    yabai -m config mouse_action1                move
    yabai -m config mouse_action2                resize
    yabai -m config mouse_drop_action            swap

# ╭───────────────────────────────────────────────────────────────────────────╮
# │                           General space settings                          │
# ╰───────────────────────────────────────────────────────────────────────────╯

    yabai -m config layout                       bsp
    yabai -m config top_padding                  8
    yabai -m config bottom_padding               8
    yabai -m config left_padding                 8
    yabai -m config right_padding                8
    yabai -m config window_gap                   8

# ╭───────────────────────────────────────────────────────────────────────────╮
# │                           Apps-specific settings                          │
# ╰───────────────────────────────────────────────────────────────────────────╯

#   Configure floating apps.
    yabai -m rule --add app="Parallels Desktop" sticky=on layer=above manage=off
    yabai -m rule --add app="Python" manage=off
    yabai -m rule --add app="Simulator" manage=off
    yabai -m rule --add app="Steam" manage=off
    yabai -m rule --add app="Color Picker" manage=off
    yabai -m rule --add app='^System Information$' manage=off
    yabai -m rule --add app='^System Preferences$' manage=off
    yabai -m rule --add title='Preferences$' manage=off
    yabai -m rule --add title='Settings$' manage=off
  # yabai -m rule --add title='QuickTime Player' manage=off
  # yabai -m rule --add title='QuickTime' manage=off
  # yabai -m rule --add app="Chrome" manage=off

#   Configure non-floating apps.
    yabai -m rule --add app="Emacs" manage=on
    yabai -m rule --add app="FaceTime" manage=on
    yabai -m rule --add app="Skype" manage=on
    yabai -m rule --add app="Blender" manage=on

# ╭───────────────────────────────────────────────────────────────────────────╮
# │                                Monocle mode                               │
# ╰───────────────────────────────────────────────────────────────────────────╯

#   Delete monocle mode lock files from previous sessions.
  # find "${TMPDIR}" -type f -perm +111 -name "yabai_${USER}_monocle_mode_*" -delete

# ╭───────────────────────────────────────────────────────────────────────────╮
# │                                   Various                                 │
# ╰───────────────────────────────────────────────────────────────────────────╯

  # yabai -m config layout stack
  # yabai -m config --space 1 layout stack
  # yabai -m space --layout stack
  # yabai -m window --focus stack.first
  # yabai -m window --focus stack.prev
  # yabai -m window --focus stack.next
  # yabai -m window --focus stack.recent
  # yabai -m window --focus stack.last

echo "yabai configuration loaded..."
