#!/usr/bin/sh
# -----------------------------------------------------------------------------

# change screen resolution
# xrandr --output eDP --mode 1920x1200


# dwm statusbar loop (run in background)
while true; do
  xsetroot -name "$(/home/vinc/.config/dwm/statusbar/statusbar.sh)"
  sleep 0.5
done &

# set background to mars
~/.fehbg &

# increase max key press frequency
xset r rate 250 50

# bind e.g. function keys
xbindkeys -f "/home/vinc/.config/x/xbindkeysrc"

# start compositing manager in background
xcompmgr &

# execute dwm on startup
# -----------------------------------------------------------------------------
exec dwm

#exec emacs
# (sleep 2 && emacs ) &
# (sleep 2 && qutebrowser ) &
# (sleep 2 && st -e "cowsay Hello there" ) &
# (sleep 2 && xterm -title "irssi" -e irssi ) &
