#!/usr/bin/sh
# -----------------------------------------------------------------------------


# dwm statusbar loop (run in background)
while true; do
  xsetroot -name "$(/home/vinc/.config/dwm/statusbar/statusbar.sh)"
  sleep 0.5
done &

# set background to mars
~/.fehbg &

# increase max key press frequency
xset r rate 250 50

# bind e.g. function keys
xbindkeys -f "/home/vinc/.config/x/xbindkeysrc"

# start compositing manager in background
xcompmgr &

# change screen resolution
# xrandr --output eDP --mode 1920x1200
# xrandr --output Virtual-1 --mode 4096x2160
# xrandr --output Virtual-1 --mode 2048x1080
# xrandr --output Virtual-1 --mode 2560x1600

# open dwm on startup
# -----------------------------------------------------------------------------
exec dwm
