#!/bin/sh
# -----------------------------------------------------------------------------
# 			            $XDG_CONFIG_HOME/zsh/zprofile
# -----------------------------------------------------------------------------

#   Source shell-independent (shared) profile config-file.
    source "$HOME/.config/shell/profile"
 
#   Define path to zsh config-file.
    export ZSHRC="$XDG_CONFIG_HOME/zsh/zshrc"
    source "$ZSHRC"

#   Define path to oh-my-zsh installation.
    export ZSH="$XDG_CONFIG_HOME/zsh/oh-my-zsh"

#   TODO ... (description)
    export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/zcompdump"

#   TODO ... (description)
  # export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# ╭───────────────────────────────────────────────────────────────────────────╮
# │ Shell command history                                                     │
# ╰───────────────────────────────────────────────────────────────────────────╯

#   Enable sharing of command history between multiple shell sessions.
    setopt sharehistory

#   Define path to command-history file.
    HISTFILE="$XDG_CACHE_HOME/zsh/history"
#   NOTE: This is overwritten in `../zsh/zshrc` for zsh-specific history.
#   TODO: Setup having only a single (shell-independent) history file?

#   Define format of timestamps for command-history.
    HIST_STAMPS="yyyy-mm-dd"

#   Define nr. of command-history entries saved in memory.
    HISTSIZE=10000

#   Define nr. of command-history entries saved to file.
    SAVEHIST=100000

# ╭───────────────────────────────────────────────────────────────────────────╮
# │ Web search-engines                                                        │
# ╰───────────────────────────────────────────────────────────────────────────╯

#   Define web search-engines, use with e.g. `web_search wikipedia euler`
    export ZSH_WEB_SEARCH_ENGINES=(
        4chan           "https://4chan.org/"
        amazon          "https://amazon.de/s?k="
        archive         "https://web.archive.org/web/*/"
        archwiki        "https://wiki.archlinux.org/?search="
        arxiv           "https://arxiv.org/search/?searchtype=all&source=header&query="
        baidu           "https://www.baidu.com/s?wd="
        bing            "https://www.bing.com/search?q="
        brave           "https://search.brave.com/search?q="
        duckduckgo      "https://www.duckduckgo.com/?q="
        ebay            "https://ebay.de/sch/"
        ecosia          "https://www.ecosia.org/search?q="
        github          "https://github.com/search?q="
        github_vm       "https://github.com/vincentmader/"
        goodreads       "https://www.goodreads.com/search?q="
        google          "https://www.google.com/search?q="
        linkedin        "https://linkedin.com/search/results/all/?keywords="
        piratebay       "https://piratebay.party/search/"
        r               "https://www.reddit.com/r/"
        reddit          "https://www.reddit.com/search/?q="
        scholar         "https://scholar.google.com/scholar?q="
        stackoverflow   "https://stackoverflow.com/search?q="
        startpage       "https://www.startpage.com/do/search?q="
        twitter         "https://twitter.com/"
        urbandictionary "https://urbandictionary.com/define.php?term="
        wikipedia       "https://en.wikipedia.org/?search="
        wiktionary      "https://en.wiktionary.org/?search="
        wolframalpha    "https://www.wolframalpha.com/input/?i="
        yahoo           "https://search.yahoo.com/search?p="
        yandex          "https://yandex.ru/yandsearch?text="
        youtube         "https://www.youtube.com/results?search_query="
    )
