#!/bin/sh

echo "ZSHENV"

    # operating system
    if [[ "$OSTYPE" == "darwin"* ]]; then
        OS="macOS"
    elif [[ "$OSTYPE" == "linux"* ]]; then
        OS="linux"
    fi

# LOCALE SETTINGS
# =============================================================================

    export LC_CTYPE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8

# ENVIRONMENT VARIABLE DEFINITION
# =============================================================================

    # user
    export USER="vinc"

    # home
    if [[ "$OS" == "linux" ]]; then
        export HOME="/Users/$USER"
    elif [[ "$OS" == "macOS" ]]; then
        export HOME="/home/$USER"
    fi

    # config, docs & code
    export CONF="$HOME/.config"
    export CODE="$DOCS/code"
    export DOCS="$HOME/Documents"


    if [[ "$OS" == "linux" ]]; then
        printf ""
    elif [[ "$OS" == "macOS" ]]; then
        eval $(/opt/homebrew/bin/brew shellenv)
    fi

# history
# -----------------------------------------------------------------------------

    HISTSIZE=10000
    SAVEHIST=10000
    HISTFILE="$HOME/.config/zsh/zsh_history"
