#!/bin/sh

echo "ZSHENV"

# ENVIRONMENT VARIABLE DEFINITION
# =============================================================================

    # user
    export USER="vinc"

    # home
    if [[ "$OSTYPE" == "darwin"* ]]; then
        export HOME="/Users/$USER"
    elif [[ "$OSTYPE" == "linux"* ]]; then
        export HOME="/home/$USER"
    fi

    # config, docs & code
    export CONF="$HOME/.config"
        # export CODE="$DOCS/code"
        # export DOCS="$HOME/Documents"

# LOCALE SETTINGS
# =============================================================================

    export LC_CTYPE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8

# 
# =============================================================================  

    if [[ "$OSTYPE" == "darwin"* ]]; then
        eval $(/opt/homebrew/bin/brew shellenv)
    elif [[ "$OSTYPE" == "linux"* ]]; then
        echo
    fi

    # rust   (TODO needed?)
    source $HOME/.cargo/env
    # emsdk  (TODO needed?)
    source $CONF/emsdk/emsdk_env.sh 2> /dev/null  # source quietly

# =============================================================================  

