#!/bin/sh


# INSTALL PACKAGES
pacman install $(cat packages_arch.txt)

# SETUP DEFAULT SHELL
#chsh -s $(which zsh)

# INSTALL PACKAGE MANAGERS
git clone https://aur.archlinux.org/yay.git /usr/src/yay
cd /usr/src/yay
makepkg -si

# SETUP PERSONAL FILES
mkdir ~/downloads
mkdir -p ~/media/pictures ~/media/videos

# auto-source xinitrc
cp $CONF/x/source_xinit /etc/X11/xinit/xinitrc

# dwm
cd ~/.config/dwm
rm config.h
sudo make clean install
    # while we're at it: dmenu
    cd $CONF/dmenu
    rm config.h
    sudo make clean install
    # ...and suckless terminal
    cd $CONF/st
    rm config.h
    sudo make clean install

# git + credential-manager (gcm)
pacman -S --needed git base-devel
    # git config http.postBuffe 524288000  # big upload buffer
tar -xvf ./gcmcore-linux_amd64.2.0.498.54650.tar.gz -C /usr/local/bin  #cgm
git-credential-manager-core configure
git config --global credential.credentialStore plaintext

# =====================================

# pip install ueberzug YuleLog
# npm install carbon-now-cli

# =====================================

# connectivity
pacman -S inetutils net-tools lsof openssh
pacman -S mongodb  # TODO: auto-choose mongodb-bin (option 4?)
# taskwarrior
    # pacman -S task tasklib tasksh timew
# rust wasm bundler, like wasm-pack (?)
    # pacman -S trunk

pacman -S scrot
    # sc-im, wifi-password, watch
    # geoiplookup, links, tree

