#!/bin/sh

HOME="/Users/vinc"
RICE="$HOME/.config/_scripts/rice"

INSTALL_PKGS=false
INSTALL_PKGS_CASK=false
INSTALL_PKGS_MACPORTS=false

INSTALL_BREW=false
INSTALL_MACPORTS=false

SOURCE_ZSHRC=true

# INSTALL BREW
# =============================================================================
if [ $INSTALL_BREW = true ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/vinc/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# INSTALL MACPORTS
# =============================================================================
if [ $INSTALL_MACPORTS = true ]; then
    cd $RICE/src
    # download source & unpack to ./src directory
    curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.7.1.tar.bz2
    tar xf MacPorts-2.7.1.tar.bz2
    rm MacPorts-2.7.1.tar.bz2
    # install
    cd ./MacPorts-2.7.1/
    ./configure
    make
    sudo make install 
    # move back to rice script directory
    cd $RICE;
fi

# INSTALL PACKAGES
# =============================================================================

# brew
if [ $INSTALL_PKGS = true ]; then
    brew install $(cat pkg_lists/brew.txt);
fi

# -----------------------------------------------------------------------------

# brew casks
if [ $INSTALL_PKGS_CASK = true ]; then
    brew install --cask $(cat pkg_lists/brew_cask.txt);
fi

# -----------------------------------------------------------------------------

# macports
if [ $INSTALL_PKGS_MACPORTS = true ]; then
    for i in $(cat pkg_lists/macports.txt); do
        sudo port install "$i";   # TODO why?
    done
fi

# VARIOUS
# =============================================================================


# for mactex install:
eval "$(/usr/libexec/path_helper)"

# source $CONF/zsh/zshrc

