#!/bin/sh
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                      $XDG_CONFIG_HOME/bash/bash_profile                   ║
# ╚═══════════════════════════════════════════════════════════════════════════╝

#   Source shell-independent (shared) profile configuration file.
    source "$HOME/.config/shell/profile"
