#!/bin/sh
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                         $XDG_CONFIG_HOME/bash/bashrc                      ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
    
#   If not running interactively: Don't do anything.
    [[ $- != *i* ]] && return

#   If running on Arch Linux: 
    if [[ "$OSTYPE" == "linux"* ]]; then
#       Auto-start Docker on login.                         (TODO Set this up.)
      # systemctl start docker  

#       Load desktop wallpaper.
      # ~/.fehbg

#       Auto-start XOrg on login.
        exec startx
    fi
