#!/bin/sh
echo "Loading BASHRC..."

# -----------------------------------------------------------------------------
# 	                $XDG_CONFIG_HOME/bash/bashrc                          |
# -----------------------------------------------------------------------------
    
# If not running interactively, don't do anything.
# =============================================================================

    # [[ $- != *i* ]] && return

# Source ~/.config/zsh/pathrc.
# =============================================================================

    # source ~/.config/zsh/pathrc.
    # source /home/vinc/.config/zsh/zshenv

# Source Cargo.
# =============================================================================

# . "$HOME/.cargo/env"

# Auto-start XOrg on login.
# =============================================================================

    # if [[ "$OSTYPE" == "darwin"* ]]; then
    #     printf ""
    # elif [[ "$OSTYPE" == "linux"* ]]; then
    #     exec startx
    #     # ~/.fehbg
    # fi

# Auto-start Docker on login.
# =============================================================================

    # systemctl start docker  
    
# Auto-start Docker on login.
# =============================================================================

    # yabai
    # TODO only start on macOS!
    # TODO only start on login!
